FROM node:18

RUN mkdir -p /app

WORKDIR /app

# RUN npm install 
COPY ./express-entrypoint.sh /scripts/express-entrypoint.sh

RUN chmod +x /scripts/express-entrypoint.sh


# CMD ["./node", "./server.js" ]
# CMD [ "npm", "run", "start" ]
ENTRYPOINT ["/scripts/express-entrypoint.sh"]

