org: gleamingmammal
console: true
service: webscraping

provider:
  name: aws
  runtime: nodejs12.x
  region: ap-northeast-1

package:
  exclude:
    - .git/**
    - test/**
    - README.md

functions:
  serverless-express:
    handler: lambda.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'