services:
  express:
    container_name: wb-express

    image: wb-express:latest

    build: 
      context: ./express
      dockerfile: Dockerfile.express

    ports:
      - "3000:3000"

    volumes:
      - ./express:/app
      - webscraping_express_node:/app/node_modules

    networks:                          #ネットワークを追加
      - default
      # .sh

  dev:
    container_name: wb-dev

    image: wb-dev:latest

    build: 
      context: .
      dockerfile: Dockerfile

    ports:
      - "25001:25001"

#bind mount の意味　名前つきvolume(データ保存先)
    volumes:
      - .:/app
      - webscraping_node_modules:/app/node_modules

    depends_on:
      - express

    networks:                          #ネットワークを追加
      - default

# 名前つきvolume
volumes:
  webscraping_node_modules:
  webscraping_express_node: